language: python
python:
- 3.8.0
services: postgresql
env:
- DJANGO=3.0 DB=postgres
before_install:
- export DJANGO_SETTINGS_MODULE=intreped.settings
install:
- pip install -r requirements.txt
- pip install django==$DJANGO --quiet
- pip install psycopg2 --quiet
- pip install djangorestframework --quiet
before_script:
- psql -c "CREATE DATABASE intreped_test;" -U postgres
deploy:
  provider: heroku
  api_key:
    secure: mhLU8In2jtscPe8b6qEx2oLiRInMNu5Yd6gn31Oac4uCWyhTJZXT1cZuxEKSp2ARAtn0gA9FVHoNH0kro4QQD210ZbqW8eYUsqwg8K6z/C5pXgijNL+NZqLaIFoAD+1LiEfTbpDVSWzxfnni1AxFPtZrvly0b+xcoKCRfeLJ3DuaP9hE5I3lIZKNrHt5X+5w1YDJLtb7EmmIWfUTJfuvAzSNipSJ1U7qoqyPg8Ug8FfKNe1qExuyqrPSIufjxwoWZdVlzQ3idSLWvsI8SiUvUfSWDoTIUDpNk57Y8p5ZCecn3w2NFudgCcqpRb0ATmuf02BqFqXJcMJovwnCSxV51xkrx5zGz+h1DJDkbrFKQrXSTXn8ekFqWEiNq2oEYdf5//xtNrEwDhYjW5ZCdITzQAlKsXZ1pvBzJVqX5Te1qdcS5JN5j+/8cwOc1oiuwnIPOXi8pWha7pd+yc/yV56K5/kKiZIz9Y9BPeRZOoRbIEe08wH3rwelk3MV39rjzpY659B8gxghDzMH2wEyAy+vASJnMgCtqCGH/QEOHkuJ0/W/5rVMUblntjL7WF/jYXrEjGKcUh/kfX10QGjJi+P7nWruSCsU60kIB4AVtcuBoYEbGqzr0z4vqRuO9okwhSETk3YNY1UlBtzeLdSiCp4C4SFqrjOpUHfZU4+eWTCUh3U=
  on:
    all_branches: true
  app: intreped
  cleanup: false
  run:
  - python3 manage.py makemigrations
  - python3 manage.py migrate
script:
- python3 manage.py test intreped
