language: python

python:
  - 3.8.0

services: postgresql

env:
  - DJANGO=3.0 DB=postgres

before_install:
  - export DJANGO_SETTINGS_MODULE=intreped.settings

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet
  - pip install djangorestframework --quiet

before_script:
  - psql -c "CREATE DATABASE intreped_test;" -U postgres

deploy:
  provider: heroku
  api_key: 
    secure: zvL8YTfdyPAYUWuE32v8Fw
  app: intreped
  skip_cleanup: true
  run:
  - 'python3 manage.py makemigrations'  
  - 'python3 manage.py migrate'

script:
  - python3 manage.py test intreped