language: python
python:
- 3.8.0
services: postgresql
env:
- DJANGO=3.0 DB=postgres
before_install:
- export DJANGO_SETTINGS_MODULE=intreped.settings
install:
- pip install -r requirements.txt
- pip install django==$DJANGO --quiet
- pip install psycopg2 --quiet
- pip install djangorestframework --quiet
before_script:
- psql -c "CREATE DATABASE intreped_test;" -U postgres
deploy:
  provider: heroku
  api_key:
    secure: lgHRaMyCnIrhcUVcPZP0O1KeeHhSVbzHuYKke6O5PRRcfaHmjZFVTtLk88waj7VGfvAxS7axnKmpRmwKFgIxMUVeqgExpx0bjVg/My/deNuCsBWX3ydy7dXzBDxsuBYsaamQqa3kANBMIRn3Za3TPOqX91M1i1OAgWfV7PyGCZNDelwNAQkuZERBBzaAqoNWK0Q4ztSMoPfaX/tcQsXmUv09no5fRMuhQ3QDGCP9IKk043E+k6omcDNiJH6AGgJVK18vLqg2NUADt7hhIb9vCleYt0AICsdFEQ1FXAaZma8nrBpS5EYFAmgF7e4Y5uJ3mp+XkV544fGaA0oJf82BP+vSdCD7tXPFdD76Y4tUDbrsc8rDBdCYAFV0Adf6xWv+kRAzRidaLRrcTx2eFIABud1yFkfPL3hFbB5uMXUQ3i5eaIvVL/h6FmPSPTmg+m1k3AOdX7y0cFL3qi2ADeA3QiO9inuAMgXkoiObXmmt5W2o1DBBGuAk0jxJp7j3uzLHcXrf7bqaviXn9IPkmV9bG408IAetdX7ima0hKZyG+zkfkeuy+k/y/6TlL59Q/Jc2o5wq9MYyi22fQ64uziLQ3IzbwvThCbQbLRcOmugJeeNeAzla2O4YXc+q9D+L9/nUaRtySyaUF3ZtOF8Pz/Jlu5gspc2YAG0oILQgvmSu3pU=
  app: intreped
  on:
    repo: intreped-learning/intreped-be
script:
- python3 manage.py test intreped
